Updating github-config

diff --git a/.github/workflows/test-pull-request.yml b/.github/workflows/test-pull-request.yml
--- a/.github/workflows/test-pull-request.yml
+++ b/.github/workflows/test-pull-request.yml
@@ -52,12 +52,19 @@ jobs:
 
   roundup:
     name: Integration Tests
+    if: ${{ always() }}
     runs-on: ubuntu-22.04
     needs: integration
     steps:
     - run: |
-        echo "Integration tests passed against all builders"
-        exit 0
+        result="${{ needs.integration.result }}"
+        if [[ $result == "success" ]]; then
+          echo "Integration tests passed against all builders"
+          exit 0
+        else
+          echo "Integration tests failed on one or more builders"
+          exit 1
+        fi
 
   upload:
     name: Upload Workflow Event Payload
